// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCST4dOKf7D6txHQAVVgzBwp-oQG9eUp-Y',
    appId: '1:1090851955881:web:03ddacc9309bd2a1ceb5b8',
    messagingSenderId: '1090851955881',
    projectId: 'rentright-890b5',
    authDomain: 'rentright-890b5.firebaseapp.com',
    storageBucket: 'rentright-890b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-QUsNsSG2WGPmN21Ow8oWh_Il1o9_p3k',
    appId: '1:1090851955881:android:b6cd87de958bca74ceb5b8',
    messagingSenderId: '1090851955881',
    projectId: 'rentright-890b5',
    storageBucket: 'rentright-890b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV5yhPibukAOIV38Wv5IS2Uf9O2Cu1Zqk',
    appId: '1:1090851955881:ios:0c7405bdea0162c6ceb5b8',
    messagingSenderId: '1090851955881',
    projectId: 'rentright-890b5',
    storageBucket: 'rentright-890b5.appspot.com',
    iosBundleId: 'com.example.loginInterface',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV5yhPibukAOIV38Wv5IS2Uf9O2Cu1Zqk',
    appId: '1:1090851955881:ios:3bf7dd6ad1ea468bceb5b8',
    messagingSenderId: '1090851955881',
    projectId: 'rentright-890b5',
    storageBucket: 'rentright-890b5.appspot.com',
    iosBundleId: 'com.example.loginInterface.RunnerTests',
  );
}
