// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH9JB525dmFGh_E3GBWB7fdmPlWmFSBFk',
    appId: '1:66507924301:web:35c3507ae9bddc07fb0d04',
    messagingSenderId: '66507924301',
    projectId: 'rent-right-4a1fb',
    authDomain: 'rent-right-4a1fb.firebaseapp.com',
    storageBucket: 'rent-right-4a1fb.appspot.com',
    measurementId: 'G-BB1TTC1DZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVzxnL3pLzFUgRzciNmA3-bcio44Xu-Ik',
    appId: '1:66507924301:android:6c14ae31cc231073fb0d04',
    messagingSenderId: '66507924301',
    projectId: 'rent-right-4a1fb',
    storageBucket: 'rent-right-4a1fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlr985Kl6zAKCYx71cP7rmgVhc3Nvueeo',
    appId: '1:66507924301:ios:c4e4523fc899c788fb0d04',
    messagingSenderId: '66507924301',
    projectId: 'rent-right-4a1fb',
    storageBucket: 'rent-right-4a1fb.appspot.com',
    iosBundleId: 'com.example.loginInterface',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlr985Kl6zAKCYx71cP7rmgVhc3Nvueeo',
    appId: '1:66507924301:ios:e644f81e734ddd48fb0d04',
    messagingSenderId: '66507924301',
    projectId: 'rent-right-4a1fb',
    storageBucket: 'rent-right-4a1fb.appspot.com',
    iosBundleId: 'com.example.loginInterface.RunnerTests',
  );
}
